---
include:
  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/config/variables.yml"

  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-build/assets.yml"
  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-build/vendors.yml"

  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-test/phpcs.yml"
  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-test/eslint.yml"
  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-test/prettier.yml"
  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-test/stylelint.yml"

  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-deploy/deployer.yml"
  
  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-post-deploy/supervisord.yml"

  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-static-cache/static-flush.yml"

  - "https://raw.githubusercontent.com/onyourmarks-agency/oym-gitlab-deploy-templates/main/stage-proxy-cache/varnish.yml"

variables:
  SSH_STAGING: "SERVER.instance.onyourmarks.tech"
  SSH_PRODUCTION: "SERVER.instance.onyourmarks.tech"
  SERVER_FOLDER_STAGING: "project.tld"
  SERVER_FOLDER_PRODUCTION: "PROJECT.staging.SERVER.instance.onyourmarks.tech"
