---
.flush_supervisord_template: &flush_supervisord_global
  stage: queue
  resource_group: supervisord
  variables:
    GIT_STRATEGY: none
  script:
    - '/bin/ssh $SSH_SERVER "sudo /usr/bin/supervisorctl restart all"'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never

flush_supervisord_production:
  <<: *flush_supervisord_global
  variables:
    SSH_SERVER: $SSH_PRODUCTION
    GIT_STRATEGY: none
  needs:
    - job: deploy_production

flush_supervisord_staging:
  <<: *flush_supervisord_global
  variables:
    SSH_SERVER: $SSH_STAGING
    GIT_STRATEGY: none
  needs:
    - job: deploy_staging
