---
.flush_supervisord_template: &flush_supervisord_global
  stage: queue
  resource_group: supervisord
  variables:
    GIT_STRATEGY: none
  script:
    - '/bin/ssh $SSH_SERVER "sudo /usr/bin/supervisorctl restart all"'

flush_supervisord_production:
  <<: *flush_supervisord_global
  variables:
    SSH_SERVER: $SSH_PRODUCTION
    GIT_STRATEGY: none
  needs:
    - job: deploy_production
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "false" || $CI_COMMIT_REF_SLUG == "master"'

flush_supervisord_staging:
  <<: *flush_supervisord_global
  variables:
    SSH_SERVER: $SSH_STAGING
    GIT_STRATEGY: none
  needs:
    - job: deploy_staging
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "false" || $CI_COMMIT_REF_SLUG != "master"'
