.clear_html_global_template: &clear_html_global
  stage: rewrite
  needs: [ ]
  script:
    - '/bin/ssh $SSH_SERVER "sudo -u apache /usr/bin/php -f $SERVER_ROOT_PATH/current/craft cacheable/clear/html"'

clear_html_production:
  <<: *clear_html_global
  variables:
    GIT_STRATEGY: none
    SSH_SERVER: $SSH_PRODUCTION
    SERVER_ROOT_PATH: $SERVER_FOLDER_PREFIX_PRODUCTION/$SERVER_FOLDER_PRODUCTION
  rules:
    - if: "$SSH_PRODUCTION != '' && $SERVER_FOLDER_PRODUCTION != ''"
      when: manual
    - when: never

clear_html_staging:
  <<: *clear_html_global
  variables:
    GIT_STRATEGY: none
    SSH_SERVER: $SSH_STAGING
    SERVER_ROOT_PATH: $SERVER_FOLDER_PREFIX_STAGING/$SERVER_FOLDER_STAGING
  rules:
    - if: "$SSH_PRODUCTION != '' && $SERVER_FOLDER_PRODUCTION != ''"
      when: manual
    - when: never
