.clear_json_global_template: &clear_json_global
  stage: rewrite
  tags: [ 'dev02' ]
  needs: [ ]
  script:
    - '/bin/ssh $SSH_SERVER "sudo -u apache /usr/bin/php -f $SERVER_ROOT_PATH/current/craft cacheable/clear/json"'

clear_json_production:
  <<: *clear_json_global
  variables:
    GIT_STRATEGY: none
    SSH_SERVER: $SSH_PRODUCTION
    SERVER_ROOT_PATH: $SERVER_FOLDER_PREFIX_PRODUCTION/$SERVER_FOLDER_PRODUCTION
  rules:
    - if: '$SSH_PRODUCTION != null && $SERVER_FOLDER_PRODUCTION != null'
      when: manual
    - when: never

clear_json_staging:
  <<: *clear_json_global
  variables:
    GIT_STRATEGY: none
    SSH_SERVER: $SSH_STAGING
    SERVER_ROOT_PATH: $SERVER_FOLDER_PREFIX_STAGING/$SERVER_FOLDER_STAGING
  rules:
    - if: '$SSH_PRODUCTION != null && $SERVER_FOLDER_PRODUCTION != null'
      when: manual
    - when: never
