---
.deploy_global_template: &deploy_global
  stage: deploy
  when: manual
  variables:
    GIT_STRATEGY: fetch
  cache:
    key: 'asset_build-$CI_COMMIT_REF_NAME-build'
    paths:
      - $BUILD_FOLDER
    policy: pull
  needs:
    - job: composer_install
      artifacts: true
      optional: true
    - job: assets_build
      artifacts: true
      optional: true
    - job: dotenv_commit
      artifacts: true
      optional: true
  environment: $DEPLOY_ENVIRONMENT
  script:
    - 'dep deploy $DEPLOY_ENVIRONMENT --branch=$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never

deploy_production:
  <<: *deploy_global
  variables:
    DEPLOY_ENVIRONMENT: production

deploy_staging:
  <<: *deploy_global
  variables:
    DEPLOY_ENVIRONMENT: staging
