.clear_varnish_template: &clear_varnish_global
  stage: varnish
  tags: [ 'dev02' ]
  needs: [ ]
  script:
    - '/bin/bash clear-varnish.sh $VARNISH_ENVIRONMENT'
  rules:
    - exists: ['clear-varnish.sh']
      when: manual
    - when: never

clear_varnish_production:
  <<: *clear_varnish_global
  variables:
    GIT_STRATEGY: fetch
    VARNISH_ENVIRONMENT: 'production'

clear_varnish_staging:
  <<: *clear_varnish_global
  variables:
    GIT_STRATEGY: fetch
    VARNISH_ENVIRONMENT: 'staging'
