---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    tags: ['*']

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-file: .gitlab-ci.yml
          _output-file: .dist/.gitlab-ci.yml
          main: ${{ steps.get_version.outputs.VERSION }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .dist/.gitlab-ci.yml
          asset_name: .gitlab-ci.yml
          tag: ${{ github.ref }}
          overwrite: true
