---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    tags: ['*']

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-file: .gitlab-ci.yml
          _output-file: dist/.gitlab-ci.yml
          master: ${{ github.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
